[
    [
        916657, 
        "dnf remove wants to downgrade packages; fails on transaction check"
    ], 
    [
        921294, 
        "dnf downgrade failure"
    ], 
    [
        922521, 
        "DNF crashes when passing packages to it via pipe"
    ], 
    [
        926871, 
        "[abrt] download_packages:AttributeError: 'Repo' object has no attribute 'cache'"
    ], 
    [
        878826, 
        "[rfe] dnf could use systemd timer unit rather than crontabs"
    ], 
    [
        922664, 
        "an option for disabling the regular metadata sync"
    ], 
    [
        892064, 
        "hourly dnf makecache too frequent, also consider using ionice"
    ], 
    [
        919769, 
        "dnf runs makecache hourly despite laptop power state"
    ], 
    [
        947258, 
        "dnf doesn't erase excluded packages"
    ], 
    [
        889202, 
        "[rfe] [repos] add support for skip_if_unavailable in repository config"
    ], 
    [
        923384, 
        "DNF uses yum web signature"
    ], 
    [
        950722, 
        "[abrt] dnf-0.3.2-1.gitf3818b4.fc20: queries.py:179:_construct_result:AttributeError: 'NoneType' object has no attribute 'query'"
    ], 
    [
        903775, 
        "Update command is deprecated but nomenclature still being used"
    ], 
    [
        887317, 
        "Dnf should beter report upgrades via obsoletes."
    ], 
    [
        914919, 
        "DNF does not have   group install"
    ], 
    [
        922667, 
        "the cronned 'dnf makecache' runs should give up quickly if there's network/checksumming issues"
    ], 
    [
        958452, 
        "dnf update Produces Log Messages Involving \"ts_done state\""
    ], 
    [
        959990, 
        "dnf dist-sync recommended in manual page but is missing from dnf's command line options"
    ], 
    [
        961549, 
        "[abrt] dnf-0.3.4-1.git03fd687.fc19: __init__.py:826:perform:Exception: (10, 'Error HTTP/FTP status code: 404', 404)"
    ], 
    [
        962188, 
        "obsoletes sometimes result in \"ERROR with transaction check vs depsolve\""
    ], 
    [
        966372, 
        "dnf prints an empty python list after running without root privileges"
    ], 
    [
        965410, 
        "\"dnf clean expire-cache\" does not have any effect"
    ], 
    [
        963627, 
        "dnf shows way over 100% in its progress bar"
    ], 
    [
        965114, 
        "When running dnf using file:/// as the media, it tries to erase packages in file:///"
    ], 
    [
        964467, 
        "group install is broken"
    ], 
    [
        963680, 
        "dnf dies with a traceback during update"
    ], 
    [
        963133, 
        "name is misprinted when package is not found"
    ], 
    [
        916662, 
        "dnf remove wants to install new packages"
    ], 
    [
        967732, 
        "[abrt] dnf-0.3.6-1.git24ce938.fc19: __init__.py:364:hashopen:DBNoSuchFileError: (2, 'Datei oder Verzeichnis nicht gefunden')"
    ], 
    [
        908491, 
        "[rfe] list recent"
    ], 
    [
        968159, 
        "repo_rpmmd.c: base:xml attr in <location> is ignored"
    ], 
    [
        974427, 
        "dnf fails on all commands with fatal error: \"global name 'os' is not defined\""
    ], 
    [
        974866, 
        "dnf crashes if neither baseurl nor mirrorlist are defined"
    ], 
    [
        976652, 
        "[abrt] UnicodeEncodeError with 'dnf info checkpolicy'"
    ], 
    [
        975858, 
        "dnf can't install in an empty installroot"
    ], 
    [
        964584, 
        "dnf doesn't replace $releasever/$basearch in mirror url"
    ], 
    [
        979942, 
        "[abrt] cli.py:1015:_configure_repos:KeyError: <repo id>"
    ], 
    [
        980227, 
        "[locking] OSError when a long running transaction gets metadata files written over by a concurrent 'dnf makecache'"
    ], 
    [
        981310, 
        "NameError: global name 'to_utf8' is not defined"
    ], 
    [
        977661, 
        "[abrt] Ctrl+C ends up with a TypeError traceback involving Base.__exit__() and Repo._handle_load()"
    ], 
    [
        984483, 
        "default to skip_if_unavailable=True"
    ], 
    [
        986545, 
        "dnf mismatching it's librepo dep in rawhide"
    ], 
    [
        979042, 
        "Slow download of packages"
    ], 
    [
        977753, 
        "Repository \"@System\" instead of \"fedora\""
    ], 
    [
        996138, 
        "[abrt] install_grouplist:UnicodeDecodeError during 'dnf group install'"
    ], 
    [
        993916, 
        "'upgrade' command displays old version numbers in summary, rather than new version numbers"
    ], 
    [
        1002798, 
        "Error when checking librepo explicit requires"
    ], 
    [
        997403, 
        "Error message instructs users to invoke 'yum' rather than 'dnf' to fix a problem"
    ], 
    [
        1002508, 
        "Updated to install any packages \"An Curl handle error: Unsupported protocol\""
    ], 
    [
        1006366, 
        "dnf makecache runs on LiveCD"
    ], 
    [
        1008444, 
        "confusing message when removing packages"
    ], 
    [
        1003220, 
        "[abrt] dnf-0.3.11-1.git7d717c7.fc19: output.py:838:_enc:TypeError: object of type 'NoneType' has no len()"
    ], 
    [
        998859, 
        "\"dnf upgrade --best\" will always install 64bits package when 32bit package is installed"
    ], 
    [
        909744, 
        "[rfe] support parallel downloads"
    ], 
    [
        984529, 
        "[rfe] fastest mirror"
    ], 
    [
        967798, 
        "[RFE] repositories costs"
    ], 
    [
        995459, 
        "conflicting requests when trying to install locally available packages"
    ], 
    [
        1013764, 
        "DNF group remove doesn't work"
    ], 
    [
        1013773, 
        "DNF group info doesn't work"
    ], 
    [
        1017278, 
        "dnf does not notice file conflicts"
    ], 
    [
        1021087, 
        "traceback during download after a transaction with obsoletes"
    ], 
    [
        878348, 
        "'dnf history undo' support missing"
    ], 
    [
        880524, 
        "[kernel] managing multiple kernel packages"
    ], 
    [
        1019957, 
        "'dnf groups summary' traceback (global name 'patterns' is not defined)"
    ], 
    [
        1020101, 
        "'dnf grouplist' throws NameError"
    ], 
    [
        1020934, 
        "traceback in \"dnf repolist\""
    ]
]